import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("https://test-third-parties.vercel.app/"),
  openGraph: {
    images: [
      {
        url: "https://scontent.ftbs10-1.fna.fbcdn.net/v/t1.6435-9/123600960_10217455830740156_4505438801488705524_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=yNhmenI39HMQ7kNvgF1keqa&_nc_ht=scontent.ftbs10-1.fna&oh=00_AYDzur7DrJLsi_a81zG5QS9AyjLHjTDxdcyrQWdRq0g3sA&oe=66E853C3",
      },
    ],
    // title: "og title",
    // description: "og Description",
  },
  twitter: {
    images: [
      {
        url: "https://scontent.ftbs10-1.fna.fbcdn.net/v/t1.6435-9/123600960_10217455830740156_4505438801488705524_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=yNhmenI39HMQ7kNvgF1keqa&_nc_ht=scontent.ftbs10-1.fna&oh=00_AYDzur7DrJLsi_a81zG5QS9AyjLHjTDxdcyrQWdRq0g3sA&oe=66E853C3",
      },
    ],
    // title: "twititer title",
    // description: "twiiter Description",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-6">
          <nav className="container">
            <ul className="flex gap-8">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
            </ul>
          </nav>
        </header>

        <main>{children}</main>
        <GoogleTagManager gtmId="GTM-NHX4M3DT" />
      </body>
    </html>
  );
}
